# Generated by Django 3.2.7 on 2021-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqli',
            name='quarantine',
            field=models.BooleanField(default=False),
        ),
    ]
